services:
  slice-manager:
    build: .
    container_name: slice-manager
    restart: unless-stopped
    ports:
      - "8000:8000"
    extra_hosts:                   
      - "host.docker.internal:host-gateway"
    environment:
      - NATS_URL=nats://nats:4222
      - VM_PLACEMENT_URL=http://vm-placement:8080/placement
      - PROMETHEUS_URL=http://10.0.10.1:9090
      - DB_HOST=host.docker.internal 
      - DB_USER=mandarina
      - DB_PASSWORD=sandia
      - DB_NAME=cloud
      - GC_INTERVAL_HOURS=6
      - IMAGES_DIR=/mnt/cloud_images
    volumes:
      # Monta la carpeta local ./keys en la ruta /app/keys dentro del contenedor
      # El ":ro" significa Read-Only (Solo lectura por seguridad)
      - ./keys:/app/keys:ro
      - /mnt/cloud_images:/mnt/cloud_images
    networks:
      - pucp_cloud_net
networks:
  pucp_cloud_net:
    external: true
