services:
  compute-provisioner:
    build: .
    container_name: compute-provisioner
    restart: unless-stopped
    environment:
      NATS_URL:        nats://nats:4222
      IMAGES_BASE_DIR: /images
      VMS_BASE_DIR:    /vms
      LOG_LEVEL:       INFO
    ports:
      - "8081:8080"
    networks:
      - pucp_cloud_net

networks:
  pucp_cloud_net:
    external: true